<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $employees = [
            [
                'employee_code' => 'EMP01',
                'name' => 'Rahul Sharma',
                'email' => 'rahul.sharma@company.com',
                'phone' => '+91-9876543210',
                'hire_date' => '2023-01-15',
                'position' => 'Software Developer',
                'department' => 'IT',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'State Bank of India',
                'account_number' => '123456789012',
                'ifsc_code' => 'SBIN0001234',
                'branch_name' => 'Connaught Place, Delhi',
                'basic_salary' => 50000.00,
                'hra' => 15000.00,
                'conveyance' => 19200.00,
                'medical' => 5000.00,
            ],
            [
                'employee_code' => 'EMP002',
                'name' => 'Priya Patel',
                'email' => 'priya.patel@company.com',
                'phone' => '+91-9876543211',
                'hire_date' => '2023-02-20',
                'position' => 'HR Manager',
                'department' => 'Human Resources',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'HDFC Bank',
                'account_number' => '234567890123',
                'ifsc_code' => 'HDFC0001234',
                'branch_name' => 'Sector 18, Noida',
                'basic_salary' => 60000.00,
                'hra' => 18000.00,
                'conveyance' => 19200.00,
                'medical' => 6000.00,
            ],
            [
                'employee_code' => 'EMP003',
                'name' => 'Amit Kumar',
                'email' => 'amit.kumar@company.com',
                'phone' => '+91-9876543212',
                'hire_date' => '2023-03-10',
                'position' => 'Project Manager',
                'department' => 'IT',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'ICICI Bank',
                'account_number' => '345678901234',
                'ifsc_code' => 'ICIC0001234',
                'branch_name' => 'Rajouri Garden, Delhi',
                'basic_salary' => 75000.00,
                'hra' => 22500.00,
                'conveyance' => 19200.00,
                'medical' => 7500.00,
            ],
            [
                'employee_code' => 'EMP004',
                'name' => 'Sneha Gupta',
                'email' => 'sneha.gupta@company.com',
                'phone' => '+91-9876543213',
                'hire_date' => '2023-04-05',
                'position' => 'UI/UX Designer',
                'department' => 'Design',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'Axis Bank',
                'account_number' => '456789012345',
                'ifsc_code' => 'UTIB0001234',
                'branch_name' => 'Karol Bagh, Delhi',
                'basic_salary' => 55000.00,
                'hra' => 16500.00,
                'conveyance' => 19200.00,
                'medical' => 5500.00,
            ],
            [
                'employee_code' => 'EMP005',
                'name' => 'Vikram Singh',
                'email' => 'vikram.singh@company.com',
                'phone' => '+91-9876543214',
                'hire_date' => '2023-05-12',
                'position' => 'Business Analyst',
                'department' => 'Business',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'Punjab National Bank',
                'account_number' => '567890123456',
                'ifsc_code' => 'PUNB0123456',
                'branch_name' => 'Lajpat Nagar, Delhi',
                'basic_salary' => 65000.00,
                'hra' => 19500.00,
                'conveyance' => 19200.00,
                'medical' => 6500.00,
            ],
            [
                'employee_code' => 'EMP006',
                'name' => 'Kavita Jain',
                'email' => 'kavita.jain@company.com',
                'phone' => '+91-9876543215',
                'hire_date' => '2023-06-18',
                'position' => 'Marketing Executive',
                'department' => 'Marketing',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'Kotak Mahindra Bank',
                'account_number' => '678901234567',
                'ifsc_code' => 'KKBK0001234',
                'branch_name' => 'Nehru Place, Delhi',
                'basic_salary' => 45000.00,
                'hra' => 13500.00,
                'conveyance' => 19200.00,
                'medical' => 4500.00,
            ],
            [
                'employee_code' => 'EMP007',
                'name' => 'Rajesh Verma',
                'email' => 'rajesh.verma@company.com',
                'phone' => '+91-9876543216',
                'hire_date' => '2023-07-25',
                'position' => 'System Administrator',
                'department' => 'IT',
                'status' => 'active',
                'password' => Hash::make('12345678'),
                'bank_name' => 'Bank of Baroda',
                'account_number' => '789012345678',
                'ifsc_code' => 'BARB0DELHI1',
                'branch_name' => 'CP, Delhi',
                'basic_salary' => 55000.00,
                'hra' => 16500.00,
                'conveyance' => 19200.00,
                'medical' => 5500.00,
            ],
            [
                'employee_code' => 'EMP008',
                'name' => 'Meera Choudhary',
                'email' => 'meera.choudhary@company.com',
                'phone' => '+91-9876543217',
                'hire_date' => '2023-08-30',
                'position' => 'Content Writer',
                'department' => 'Marketing',
                'status' => 'active',
                'password' => Hash::make('password123'),
                'bank_name' => 'IDBI Bank',
                'account_number' => '890123456789',
                'ifsc_code' => 'IBKL0001234',
                'branch_name' => 'Dwarka, Delhi',
                'basic_salary' => 40000.00,
                'hra' => 12000.00,
                'conveyance' => 19200.00,
                'medical' => 4000.00,
            ],
        ];

        foreach ($employees as $employee) {
            // Prevent duplicate seed errors on unique fields when seeding multiple times
            Employee::updateOrCreate(
                ['employee_code' => $employee['employee_code']],
                $employee
            );
        }
    }
}
